### ISSUE TITLE
The stats bar are showing rectangular symbols

### ISSUE THREAD

**Issue by haiming940528** [ValMobile/RLCraft#7]
So my server is running on 1.17.1-paper-391, and my client is also on 1.17.1, with the resourcepack installed. But after joining the world, the stats bar are not displaying correctly, like thirst I suppose. Instead, weird white rectangular symbols are displayed there. 
I didn't install the resourcepack via the config file but directly download it from dropbox.

**Comment by ValMobile** [comment]
Issue closed, user had "Force Unicode Font: ON" when it should be forced off.
